### ISSUE TITLE
Mybe is a bug,when open the Beehave panel it will break

### ISSUE THREAD

**Issue by DataOod** [bitbrain/beehave#351] opened 2024-08-01 10:38 UTC
Godot version: 4.2.2

When open the Beehave tree panel it break.
if don't , tree will run fine but open the debug panel .when tree are going run next composite it break.
don't know dose is a bug.

![10](https://github.com/user-attachments/assets/3ce5c6b6-0fac-41f9-9340-f9d4b53a8652)
![11](https://github.com/user-attachments/assets/bcb35d8b-de9b-426b-a428-fa2d6fa0e56c)
![12](https://github.com/user-attachments/assets/8a207f3f-8a4a-4e76-b524-341c0b108dda)
![13](https://github.com/user-attachments/assets/54f6a575-7048-4503-8860-7dcbab8ba73a)

**Comment by DataOod** [comment] 2024-08-01 12:50
Soryy,I don't know why it now running fine and not break anymore.

**Comment by dagrooms52** [comment] 2024-09-11 15:51
I'm getting the same error. It only appears when running the beehave debugger, the game continues working without errors if I don't open the debug panel.

**Comment by dagrooms52** [comment] 2024-09-11 16:45
This was caused by an ActionLeaf extension script not returning any result; I added `return SUCCESS` which fixed the bug.

There was no warning in the engine for lack of a return value. This could be fixed by adding the type hint `-> int` to the `tick(_1, _2)` override. This is present in the template function but is not copied by Godot by default. To enable this, check `add type hints` in `editor settings > completion`.

To locate the broken script in a large tree, you can delete higher branches iteratively and see if the issue continues to repro.

**Comment by bitbrain** [comment] 2024-09-18 14:12
@dagrooms52 can you confirm that this was indeed user error or can you observe this as a bug from the addon itself?

**Comment by dagrooms52** [comment] 2024-09-18 14:28
It's a user error. 

The error itself is somewhat hidden, there is no warning that the overridden function isn't returning a required value using default Godot settings, but that is a problem with the engine settings not the plugin.

**Closed as completed** 2024-09-30 08:19 UTC
Labels: 🐛 bug
