### ISSUE TITLE
Addon errors on first load

### ISSUE THREAD

**Issue by Shadowblitz16** [bitbrain/beehave#270] opened 2023-12-14 03:43 UTC
Godot version: v4.2.1.stable.official [b09f793f5]

**Describe the bug**
Errors

**To Reproduce**
1. Open godot 4.2.1
2. Download beehave from asset browser
3. Enable it in project settings
4. 
```
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger_tab.gd:-1 - Compile Error: 
  res://addons/beehave/debug/graph_edit.gd:43 - Parse Error: Identifier "arrange_nodes_button_hidden" not declared in the current scope.
  res://addons/beehave/debug/graph_edit.gd:50 - Parse Error: Function "get_zoom_hbox()" not found in base self.
  res://addons/beehave/debug/debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/debug/debugger.gd" with error "Compilation failed". (User)
```

**Expected behavior**
No errors

**Screenshots**
![image](https://github.com/bitbrain/beehave/assets/2453707/77967c64-042b-4b42-b99c-efb1f025640b)

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04
 - Browser: firefox
 - Version 121.0

**Additional context**
I recently tried updating from godot 4.2 mono to godot 4.2.1 non mono to try to get this plugin to work.

**Comment by bitbrain** [comment] 2023-12-14 08:12
I assumed that marking an addon as 4.1 only will hide it from future versions - this does not seem to be the case. Will try to update it today. @Shadowblitz16 can you confirm latest 2.7.9 works for you? (downloadable here)

**Comment by bitbrain** [comment] 2023-12-14 08:41
@Shadowblitz16 can you try again with https://godotengine.org/asset-library/asset/1349?

**Comment by Shadowblitz16** [comment] 2023-12-14 18:54
@bitbrain no error when enabling the plugin now, but I get this when I try to run it...
![image](https://github.com/bitbrain/beehave/assets/2453707/034ab4be-2352-4bf1-a9f0-e78b9ffc6fb5)
This is how I updated...
1. Disable the plugin
2. Disable the autoloads
3. Delete the autoloads
4. Delete the addons folder and the script templates folder
5. Drag the addons folder and the script templates from the link your provided to my project root
6. Run scene

**Comment by Shadowblitz16** [comment] 2023-12-14 19:01
I tried doing the above and deleting my scripts folder which extends classes in beehave
Then I just copy and pasted the folder in and starting the editor
Even though I don't have the scripts, plugins enabled or the autoloads added I get this...
```
  res://addons/beehave/nodes/beehave_tree.gd:91 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:96 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:133 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:138 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:261 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/debug/global_debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/debug/global_debugger.gd" with error "Parse error". (User)
  res://addons/beehave/nodes/beehave_tree.gd:91 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:96 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:133 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:138 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:261 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/metrics/beehave_global_metrics.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/metrics/beehave_global_metrics.gd" with error "Parse error". (User)
  Cannot navigate to 'res://scripts/' as it has not been found in the file system!```
```
here is the project with everything related to your plugin disabled and removed...
[AstroWars.zip](https://github.com/bitbrain/beehave/files/13677218/AstroWars.zip)

Just do the following...
1. close the godot editor
2. copy the addons folder and the script templates to the project root
3. start the godot editor
4. load my project
5. enable the plugin
6. you should get errors by this point.

**Comment by bitbrain** [comment] 2023-12-15 16:12
Can you delete the .godot folder, too?

**Comment by Shadowblitz16** [comment] 2023-12-16 02:26
Tried it and..
```
Godot Engine v4.2.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/horizontal_layout.svg-d2a7af351e44f9bf61d0c938b6f47fac.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_bottom.svg-e5c5c61b642a79ab9c2b66ff56603d34.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_left.svg-69cd927c4db555f1edbb8d1f553ea2fd.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_right.svg-f760bd8be2dd613d0d3848c998c92a2a.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_top.svg-d1b336cdc6a0dd570305782a1e56f61d.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/vertical_layout.svg-1a08fee4b09812a05bcf3defb8afcc4c.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/action.svg-e8a91246d0ba9ba3cf84290d65648f06.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/blackboard.svg-18d4dfd4f6de558de250b67251ff1e69.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_bt.svg-8537bebd1c5f62dca3d7ee7f17efeed4.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_composite.svg-43f66e63a7ccfa5ac8ec6da0583b3246.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_decorator.svg-79d598d6456f32724156248e09d6eaf3.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_leaf.svg-c740ecab6cfae632574ca5e39e46fd2e.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/condition.svg-57892684b10a64086f68c09c388b17e5.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/failer.svg-9a62b840e1eacc0437e7a67b14a302e4.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/inverter.svg-1f1b976d95de42c4ad99a92fa9a6c5d0.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/limiter.svg-b4c7646605c46f53c5e403fe21d8f584.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/selector.svg-78bccfc448bd1676b5a29bfde4b08e5b.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/selector_random.svg-d52fea1352c24483ecd9dc8609cf00f3.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/selector_reactive.svg-dd3b8fb8cd2ffe331605aaad1e021cc0.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/sequence.svg-76e5600611900cc81e9ec286977b8c6a.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/sequence_random.svg-58cee9098c622ef87db941279206422a.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/sequence_reactive.svg-7d384ca290f7934adb9e17d9e7116b6c.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/succeeder.svg-e5cf6f6e04b9b862b82fd2cb479272aa.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/tree.svg-c0b20ed88b2fe300c0296f7236049076.editor.meta'
  res://addons/beehave/nodes/beehave_tree.gd:91 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:96 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:133 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:138 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:261 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/debug/global_debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/debug/global_debugger.gd" with error "Parse error". (User)
  res://addons/beehave/nodes/beehave_tree.gd:91 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:96 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:133 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:138 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:261 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/metrics/beehave_global_metrics.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/metrics/beehave_global_metrics.gd" with error "Parse error". (User)```

**Comment by bitbrain** [comment] 2023-12-16 13:50
This looks to me like a Godot bug. Try restarting Godot a couple of times. There needs to be an 'importing resources' progress bar that re-creates the cache.

**Comment by Shadowblitz16** [comment] 2023-12-17 06:24
> This looks to me like a Godot bug. Try restarting Godot a couple of times. There needs to be an 'importing resources' progress bar that re-creates the cache.

I already tried restarting godot.
Can you make the bug report and link it here?
I don't know what the bug exactly is so I don't know how to report it

**Comment by Shadowblitz16** [comment] 2023-12-17 21:15
I think it's a initialization order bug.
I got the thing to work but I still get the errors the first time I enable the plugin

**Comment by Shadowblitz16** [comment] 2023-12-31 05:10
Any news on this?
I tried behavior toolkit addon and that seems to work without errors.

**Comment by Shadowblitz16** [comment] 2023-12-31 18:53
I tried with new project...
```
Godot Engine v4.2.1.stable.official (c) 2007-present Juan Linietsky, Ariel Manzur & Godot Contributors.
  modules/gltf/register_types.cpp:63 - Blend file import is enabled in the project settings, but no Blender path is configured in the editor settings. Blend files will not be imported.
--- Debug adapter server started ---
--- GDScript language server started on port 6005 ---
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/horizontal_layout.svg-d2a7af351e44f9bf61d0c938b6f47fac.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_bottom.svg-e5c5c61b642a79ab9c2b66ff56603d34.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_left.svg-69cd927c4db555f1edbb8d1f553ea2fd.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_right.svg-f760bd8be2dd613d0d3848c998c92a2a.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/port_top.svg-d1b336cdc6a0dd570305782a1e56f61d.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/vertical_layout.svg-1a08fee4b09812a05bcf3defb8afcc4c.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/action.svg-e8a91246d0ba9ba3cf84290d65648f06.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/blackboard.svg-18d4dfd4f6de558de250b67251ff1e69.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_bt.svg-8537bebd1c5f62dca3d7ee7f17efeed4.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_composite.svg-43f66e63a7ccfa5ac8ec6da0583b3246.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_decorator.svg-79d598d6456f32724156248e09d6eaf3.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/category_leaf.svg-c740ecab6cfae632574ca5e39e46fd2e.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/condition.svg-57892684b10a64086f68c09c388b17e5.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/failer.svg-9a62b840e1eacc0437e7a67b14a302e4.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/inverter.svg-1f1b976d95de42c4ad99a92fa9a6c5d0.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/limiter.svg-b4c7646605c46f53c5e403fe21d8f584.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/selector.svg-78bccfc448bd1676b5a29bfde4b08e5b.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/selector_random.svg-d52fea1352c24483ecd9dc8609cf00f3.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/selector_reactive.svg-dd3b8fb8cd2ffe331605aaad1e021cc0.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/sequence.svg-76e5600611900cc81e9ec286977b8c6a.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/sequence_random.svg-58cee9098c622ef87db941279206422a.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/sequence_reactive.svg-7d384ca290f7934adb9e17d9e7116b6c.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/succeeder.svg-e5cf6f6e04b9b862b82fd2cb479272aa.editor.meta'
  Missing required editor-specific import metadata for a texture (please reimport it using the 'Import' tab): 'res://.godot/imported/tree.svg-c0b20ed88b2fe300c0296f7236049076.editor.meta'
  res://addons/beehave/nodes/beehave_tree.gd:91 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:96 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:133 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:138 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:261 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/debug/global_debugger.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/debug/global_debugger.gd" with error "Parse error". (User)
  res://addons/beehave/nodes/beehave_tree.gd:91 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:96 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:133 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:138 - Parse Error: Identifier "BeehaveGlobalDebugger" not declared in the current scope.
  res://addons/beehave/nodes/beehave_tree.gd:261 - Parse Error: Identifier "BeehaveGlobalMetrics" not declared in the current scope.
  res://addons/beehave/metrics/beehave_global_metrics.gd:-1 - Compile Error: 
  modules/gdscript/gdscript.cpp:2788 - Failed to load script "res://addons/beehave/metrics/beehave_global_metrics.gd" with error "Parse error". (User)
```

**Comment by bitbrain** [comment] 2024-01-02 11:54
@Shadowblitz16 yes, the reason is that behaviour toolkit probably currently does not have a realtime debugger in the Godot editor. The errors you are seeing are dependency issues that can be worked around by trying some of the following things:

- delete .godot folder and reopen project
- restart project multiple times until error disappears

This is not necessarily an issue with Beehave but more an issue of how Godot does lifecycle. We require e.g. both `BeehaveGlobalMetrics` and `BeehaveGlobalDebugger` to be loaded before `Beehave` class is loaded, but in case the class cache in .godot is not initialised properly, this causes problems.

To solve this properly, we would need to completely rewrite the debugger from scratch, without relying on `BeehaveGlobalDebugger` and `BeehaveGlobalMetrics` (perhaps by using static variables?) or more hacky by using less static typing but do lookup hacks via `ClassDB` - FYI @DarkMessiah

**Comment by bitbrain** [comment] 2024-01-03 08:05
This is originally caused by a bug in Godot but will be fixed by https://github.com/godotengine/godot/pull/86453

**Closed as completed** 2024-01-06 11:47 UTC
Labels: 🐛 bug
